[[shards]]
name  = "sh0"
idx = 0
Address = "localhost:8080"

[[shards]]
name  = "sh1"
idx = 1
Address = "localhost:8081"

[[shards]]
name  = "sh2"
idx = 2
Address = "localhost:8082"


[[shards]]
name  = "sh3"
idx = 3
Address = "localhost:8083"